const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
function setup(options={}){
 const input={value:'Mensagem real',dataset:{}};let toast='';
 const c={console,Map,Date,Number,String,Promise,URL,planoEmpresaAtual:()=>({nome:'Mensal'}),usoPlanoEmpresa(){},saldoPlano(){},empresaLogada:()=>options.company||{},vagasDaEmpresa:()=>[],PLANOS_EMPRESA:{basico:{nome:'Grátis',vagas:3,destaques:0,urgentes:0,confidenciais:0}},window:{},document:{addEventListener(){},querySelector(){return null},querySelectorAll(){return[]},getElementById(id){return id.startsWith('chatTextoEM_')?input:null}},sessionStorage:{getItem(){return null}},EMPREGAMAIS_SUPABASE_URL:'https://example.test',sbHeadersEM:()=>({}),sbGarantirSessaoEM:async()=> 'valid',sbBuscarMinhaEmpresaEM:async()=>({id:'company'}),sbVagasCacheEM:[{id:'deleted',empresaId:'company'},{id:'other',empresaId:'other'}],sbMapVagaEM:r=>r,sbJsonEM:options.request||(async()=>[]),gravar(){},sbCarregarVagasEmpresaAtualEM(){},sbCarregarCandidaturasEM(){},enviarMensagemCandidaturaEM(){},prepararPublicacao(){},sbDadosVagaAtualEM:async()=>options.publication||{},criarPedidoPlanoCheckout(){},continuarPagamentoPlano(){},assinarPremiumCandidatoEM(){},selecionarPlano(){},abrirCheckoutPlano(){},papelAtual:()=> 'candidato',mostrarToast:m=>{toast=m},irPara(){},nums:x=>String(x||'').replace(/\D/g,''),valorSalario:x=>Number(x)||0};vm.createContext(c);vm.runInContext(fs.readFileSync('novo/assets/js/portal-workflows.js','utf8'),c);return {c,input,toast:()=>toast};
}
test('company catalog queries the company id and replaces removed jobs',async()=>{const urls=[];const {c}=setup({request:async url=>{urls.push(url);return[{id:'live',empresaId:'company'}]}});const rows=await c.sbCarregarVagasEmpresaAtualEM();assert.equal(rows.length,1);assert.match(urls[0],/empresa_id=eq.company/);assert.equal(c.sbVagasCacheEM.some(v=>v.id==='deleted'),false);assert.equal(c.sbVagasCacheEM.some(v=>v.id==='other'),true);});
test('failed message submission keeps the draft and does not announce success',async()=>{const {c,input,toast}=setup({request:async()=>{throw Error('offline')}});await c.enviarMensagemCandidaturaEM('application');assert.equal(input.value,'Mensagem real');assert.match(toast(),/Não foi possível enviar/);assert.equal(input.dataset.sending,undefined);});
test('publication rejects dangerous external schemes and invalid salary ranges',async()=>{const a=setup({publication:{cargo:'Analista',descricao:'Atividades',requisitos:'Experiência',candidaturaTipo:'externo',candidaturaLink:'javascript:alert(1)'}});await assert.rejects(a.c.sbDadosVagaAtualEM(),/Link de candidatura inválido/);const b=setup({publication:{cargo:'Analista',descricao:'Atividades',requisitos:'Experiência',candidaturaTipo:'portal',salario:'5000',salarioMax:'2000'}});await assert.rejects(b.c.sbDadosVagaAtualEM(),/salário máximo/);});

test("expired paid plans use free limits",()=>{const {c}=setup({company:{planoValidoAte:"2020-01-01"}});assert.equal(c.planoEmpresaAtual().nome,"Grátis");assert.equal(c.saldoPlano().vagas,3);});
