import { createClient } from 'npm:@supabase/supabase-js@2';
import webpush from 'npm:web-push@3.6.7';
const supabaseUrl=Deno.env.get('SUPABASE_URL')!,serviceKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const publicKey=Deno.env.get('VAPID_PUBLIC_KEY')!,privateKey=Deno.env.get('VAPID_PRIVATE_KEY')!,subject=Deno.env.get('VAPID_SUBJECT')||'mailto:suporte@empregamais.com.br';
webpush.setVapidDetails(subject,publicKey,privateKey);
const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false}});
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{...cors,'Content-Type':'application/json'}});
async function actor(req:Request){const a=req.headers.get('Authorization')||'';if(!a.startsWith('Bearer '))throw Error('Não autenticado.');const c=createClient(supabaseUrl,Deno.env.get('SUPABASE_ANON_KEY')||'',{auth:{persistSession:false}});const {data,error}=await c.auth.getUser(a.slice(7));if(error||!data.user)throw Error('Sessão inválida.');return data.user}
async function sendToUsers(ids:string[],payload:Record<string,unknown>){const u=[...new Set(ids.filter(Boolean))];if(!u.length)return{sent:0};const {data:subs}=await admin.from('push_subscriptions').select('*').in('user_id',u).eq('enabled',true);let sent=0;for(const s of subs||[]){try{await webpush.sendNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},JSON.stringify(payload));sent++}catch(e:any){if([404,410].includes(Number(e?.statusCode)))await admin.from('push_subscriptions').delete().eq('endpoint',s.endpoint)}}return{sent}}
async function notifyProcess(u:any,id:string,kind:string){const {data:c,error}=await admin.from('candidaturas').select('*').eq('id',id).maybeSingle();if(error||!c)throw Error('Candidatura não encontrada.');const {data:e}=await admin.from('empresas').select('*').eq('id',c.empresa_id).maybeSingle();const emp=String(c.empresa_user_id||'')===String(u.id)||String(e?.user_id||'')===String(u.id),cand=String(c.candidato_user_id||'')===String(u.id);if(!emp&&!cand)throw Error('Sem permissão para esta candidatura.');const target=emp?c.candidato_user_id:c.empresa_user_id;if(!target)throw Error('Destinatário não identificado.');const {data:p}=await admin.from('push_preferences').select('*').eq('user_id',target).maybeSingle();if(p&&p.enabled===false)return{sent:0,disabled:true};if(kind==='mensagem'&&p&&p.mensagens===false)return{sent:0,disabled:true};return sendToUsers([target],{title:kind==='entrevista'?'Entrevista agendada':'Atualização da candidatura',body:kind==='entrevista'?'Uma entrevista foi agendada para você no EmpregaMais.':`Seu processo seletivo foi atualizado para: ${c.status||'nova etapa'}.`,tag:`candidatura-${c.id}`,url:'./?pagina=candidaturas'})}
async function notifyNewJob(u:any,id:string){const {data:v,error}=await admin.from('vagas').select('*').eq('id',id).maybeSingle();if(error||!v)throw Error('Vaga não encontrada.');if(String(v.status||'').toLowerCase()!=='aprovada')return{sent:0,pending:true};const {data:e}=await admin.from('empresas').select('*').eq('id',v.empresa_id).maybeSingle();const isAdmin=u.app_metadata?.role==='admin'||u.user_metadata?.role==='admin';if(!isAdmin&&String(e?.user_id||v.empresa_user_id||'')!==String(u.id))throw Error('Sem permissão para esta vaga.');const {data:cs}=await admin.from('candidatos').select('user_id,perfil,cidade').not('user_id','is',null);const area=String(v.area||'').toLowerCase(),city=String(v.cidade||'').toLowerCase(),mod=String(v.modalidade||'').toLowerCase();const ids=(cs||[]).filter(c=>{const p=c.perfil&&typeof c.perfil==='object'?c.perfil:{};const ca=String(p.area||'').toLowerCase(),cc=String(c.cidade||p.cidade||'').toLowerCase(),cm=String(p.modalidade||((Array.isArray(p.modalidades)?p.modalidades:[]).join(' '))).toLowerCase();return(!area||!ca||ca.includes(area)||area.includes(ca))&&(!city||!cc||city===cc)&&(!mod||!cm||cm.includes(mod)||mod.includes(cm))}).map(c=>c.user_id);const {data:ps}=await admin.from('push_preferences').select('user_id,vagas_compativeis,enabled').in('user_id',ids);const finalIds=ids.filter(id=>!ps?.some(p=>p.user_id===id)||ps.some(p=>p.user_id===id&&p.enabled!==false&&p.vagas_compativeis!==false));return sendToUsers(finalIds,{title:'Nova vaga para você',body:`${v.cargo||v.titulo||'Nova oportunidade'}${v.cidade?` · ${v.cidade}${v.estado?' - '+v.estado:''}`:''}`,tag:`vaga-${v.id}`,url:`./?pagina=vaga&id=${encodeURIComponent(v.id)}`})}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});try{const u=await actor(req),b=await req.json();if(b.action==='processo')return json(await notifyProcess(u,String(b.candidatura_id||''),String(b.kind||'status')));if(b.action==='nova_vaga')return json(await notifyNewJob(u,String(b.vaga_id||'')));return json({error:'Ação inválida.'},400)}catch(e:any){return json({error:e?.message||'Erro interno.'},400)}});