import { getCompany,getCompanyJobs,getApplications,updateApplication } from '../services/supabase.js';
let apps=[],jobs=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
export function renderCandidates(){
 return `<main class="page"><a class="page-back" href="./?pagina=vagas-empresa">← Minhas vagas</a><header class="form-hero candidates-hero"><span>PROCESSO SELETIVO</span><h1>Candidatos</h1><p>Analise candidaturas e acompanhe cada etapa do recrutamento.</p></header><section class="panel"><div class="toolbar candidates-tools"><label class="search"><span>⌕</span><input id="candSearch" placeholder="Buscar candidato"></label><select id="candJob"><option value="">Todas as vagas</option></select><select id="candStatus"><option value="">Todos os status</option></select><select id="candFit"><option value="">Toda aderência</option><option value="80">80% ou mais</option><option value="60">60% ou mais</option><option value="40">40% ou mais</option></select></div><div id="candidateList"><p>Carregando candidaturas...</p></div></section></main>`;
}
function title(id){const v=jobs.find(x=>String(x.id)===String(id));return v?.cargo||v?.titulo||'Vaga'}
function render(){
 const box=document.querySelector('#candidateList'),q=(document.querySelector('#candSearch')?.value||'').toLowerCase(),job=document.querySelector('#candJob')?.value||'',st=document.querySelector('#candStatus')?.value||'',fit=Number(document.querySelector('#candFit')?.value||0);
 const list=apps.filter(c=>(!q||[c.candidato_nome,c.candidato_email].join(' ').toLowerCase().includes(q))&&(!job||String(c.vaga_id)===job)&&(!st||String(c.status)===st)&&(!fit||Number(c.aderencia||0)>=fit));
 box.innerHTML=list.length?'<div class="candidate-grid">'+list.map(c=>`<article class="candidate-card"><div class="candidate-top"><div class="avatar">${esc((c.candidato_nome||'C')[0].toUpperCase())}</div><div><h3>${esc(c.candidato_nome||'Candidato')}</h3><p>${esc(title(c.vaga_id))}</p></div><span class="candidate-status status-${esc(String(c.status||'Em avaliação').toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g,'').replace(/[^a-z0-9]+/g,'-'))}">${esc(c.status||'Em avaliação')}</span></div><div class="candidate-data"><div><span>ADERÊNCIA</span><strong>${esc(c.aderencia??'—')}${c.aderencia!=null?'%':''}</strong></div><div><span>CURRÍCULO</span><strong>${esc(c.curriculo_origem||'Perfil')}</strong></div><div><span>ATUALIZAÇÃO</span><strong>${c.atualizado_em?new Date(c.atualizado_em).toLocaleDateString('pt-BR'):'—'}</strong></div></div><div class="candidate-contact">${c.candidato_email?'<a href="mailto:'+esc(c.candidato_email)+'">E-mail</a>':''}${c.candidato_telefone?'<a target="_blank" href="https://wa.me/55'+String(c.candidato_telefone).replace(/\D/g,'')+'">WhatsApp</a>':''}<button data-cv="${esc(c.id)}">Ver currículo</button></div><div class="candidate-actions"><button data-status="Em avaliação" data-id="${esc(c.id)}">Em análise</button><button data-interview="${esc(c.id)}">Entrevista</button><button data-status="Aprovado" data-id="${esc(c.id)}" class="approve">Aprovar</button><button data-status="Reprovado" data-id="${esc(c.id)}" class="reject">Reprovar</button><button data-status="Contratado" data-id="${esc(c.id)}" class="hire">Contratado</button></div></article>`).join('')+'</div>':'<div class="empty"><strong>Nenhum candidato encontrado</strong><p>Ajuste os filtros ou aguarde novas candidaturas.</p></div>';
 box.querySelectorAll('[data-status]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{const n=await updateApplication(b.dataset.id,b.dataset.status),i=apps.findIndex(x=>String(x.id)===String(n.id));if(i>=0)apps[i]=n;render()}catch(e){alert(e.message);b.disabled=false}});
 box.querySelectorAll('[data-cv]').forEach(b=>b.onclick=()=>{const c=apps.find(x=>String(x.id)===b.dataset.cv);openCV(c)});box.querySelectorAll('[data-interview]').forEach(b=>b.onclick=()=>openInterview(apps.find(x=>String(x.id)===b.dataset.interview)));
}
function cvSection(title,value){if(value==null||value===''||(Array.isArray(value)&&!value.length))return '';const txt=Array.isArray(value)?value.map(x=>typeof x==='object'?Object.values(x).filter(Boolean).join(' · '):x).join('\n'):typeof value==='object'?Object.entries(value).map(([k,v])=>k+': '+(Array.isArray(v)?v.join(', '):v)).join('\n'):value;return '<div class="cv-section"><span>'+esc(title)+'</span><p>'+esc(txt).replace(/\n/g,'<br>')+'</p></div>'}
function openCV(c){document.querySelector('#cvModal')?.remove();const d=document.createElement('div');d.id='cvModal';d.className='cv-modal';const cv=c?.curriculo||c?.perfil_profissional||{},hist=Array.isArray(c?.historico)?c.historico:[];d.innerHTML=`<div class="cv-back"></div><section><button class="cv-close">×</button><span>CURRÍCULO DO CANDIDATO</span><h2>${esc(c?.candidato_nome||'Candidato')}</h2><p>${esc(c?.candidato_email||'')} ${c?.candidato_telefone?' · '+esc(c.candidato_telefone):''}</p><div class="cv-body">${cvSection('Resumo profissional',cv.resumo||cv.objetivo||cv.sobre)}${cvSection('Experiência',cv.experiencias||cv.experiencia)}${cvSection('Formação',cv.formacao||cv.escolaridade)}${cvSection('Cursos e competências',cv.cursos||cv.competencias||cv.habilidades)}${!Object.keys(cv).length?'<div class="cv-section"><p>Currículo estruturado não disponível para esta candidatura.</p></div>':''}<div class="cv-section"><span>HISTÓRICO DO PROCESSO</span><div class="timeline">${hist.length?hist.slice().reverse().map(h=>'<div><b>'+esc(h.status||'Atualização')+'</b><small>'+esc(h.data?new Date(h.data).toLocaleString('pt-BR'):'')+'</small></div>').join(''):'<p>Sem movimentações registradas.</p>'}</div></div></div></section>`;document.body.appendChild(d);d.querySelector('.cv-back').onclick=d.querySelector('.cv-close').onclick=()=>d.remove()}
function openInterview(c){if(!c)return;document.querySelector('#interviewModal')?.remove();const d=document.createElement('div');d.id='interviewModal';d.className='cv-modal';const current=c.entrevista||{};d.innerHTML=`<div class="cv-back"></div><section class="interview-box"><button class="cv-close">×</button><span>AGENDAR ENTREVISTA</span><h2>${esc(c.candidato_nome||'Candidato')}</h2><form id="interviewForm" class="interview-form"><label>Data<input name="data" type="date" value="${esc(current.data||'')}" required></label><label>Horário<input name="hora" type="time" value="${esc(current.hora||'')}" required></label><label>Formato<select name="formato"><option>Online</option><option>Presencial</option><option>Telefone</option></select></label><label class="wide">Local ou link<input name="local" value="${esc(current.local||current.link||'')}" placeholder="Link da reunião ou endereço"></label><label class="wide">Observações<textarea name="observacoes" rows="3">${esc(current.observacoes||'')}</textarea></label><button type="submit">Salvar entrevista</button></form></section>`;document.body.appendChild(d);d.querySelector('.cv-back').onclick=d.querySelector('.cv-close').onclick=()=>d.remove();const form=d.querySelector('#interviewForm');form.formato.value=current.formato||'Online';form.onsubmit=async ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(form).entries());if(new Date(data.data+'T'+data.hora)<new Date()){alert('Escolha uma data e horário futuros.');return}const btn=form.querySelector('button');btn.disabled=true;try{const n=await updateApplication(c.id,'Entrevista agendada',{entrevista:data}),i=apps.findIndex(x=>String(x.id)===String(n.id));if(i>=0)apps[i]=n;d.remove();render()}catch(e){alert(e.message);btn.disabled=false}}}
export async function hydrateCandidates(){
 const box=document.querySelector('#candidateList');try{const company=await getCompany();if(!company)throw new Error('Sessão empresarial necessária.');[jobs,apps]=await Promise.all([getCompanyJobs(company),getApplications(company)]);const js=document.querySelector('#candJob'),ss=document.querySelector('#candStatus');js.innerHTML='<option value="">Todas as vagas</option>'+jobs.map(v=>'<option value="'+esc(v.id)+'">'+esc(v.cargo||v.titulo||'Vaga')+'</option>').join('');const statuses=[...new Set(apps.map(x=>x.status).filter(Boolean))];ss.innerHTML='<option value="">Todos os status</option>'+statuses.map(x=>'<option>'+esc(x)+'</option>').join('');const wanted=new URLSearchParams(location.search).get('vaga');if(wanted)js.value=wanted;render();document.querySelector('#candSearch').oninput=render;js.onchange=render;ss.onchange=render;document.querySelector('#candFit').onchange=render}catch(e){box.innerHTML='<div class="empty error"><strong>Não foi possível carregar candidatos</strong><p>'+esc(e.message)+'</p></div>'}}
