import { getCompany,getCompanyJobs,getApplications,jobStatus } from '../services/supabase.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
export function renderCompanyHome(){
 return `<main class="page"><header class="dashboard-hero"><div><span>PAINEL DA EMPRESA</span><h1 id="companyWelcome">Visão geral</h1><p>Acompanhe o recrutamento e acesse rapidamente as principais tarefas.</p></div><a class="publish" href="./?pagina=publicar-vaga">+ Publicar nova vaga</a></header><section id="dashboardKpis" class="dashboard-kpis"><article><span>CARREGANDO</span><strong>—</strong></article></section><div class="dashboard-grid"><section class="panel"><div class="panel-head"><div><h2>Processos seletivos</h2><p>Vagas em andamento e movimentação de candidatos.</p></div><a href="./?pagina=vagas-empresa">Ver todas</a></div><div id="dashboardJobs">Carregando...</div></section><aside class="panel quick-panel"><h2>Ações rápidas</h2><a href="./?pagina=publicar-vaga"><b>＋</b><span>Publicar vaga<small>Criar nova oportunidade</small></span></a><a href="./?pagina=vagas-empresa"><b>▣</b><span>Minhas vagas<small>Gerenciar oportunidades</small></span></a><a href="./?pagina=candidatos-empresa"><b>♟</b><span>Candidatos<small>Acompanhar processos</small></span></a></aside></div><section class="panel performance-panel"><div class="panel-head"><div><h2>Desempenho do recrutamento</h2><p>Indicadores calculados a partir das candidaturas da empresa.</p></div></div><div id="performanceMetrics" class="performance-grid"></div></section></main>`;
}
export async function hydrateCompanyHome(){
 const k=document.querySelector('#dashboardKpis'),list=document.querySelector('#dashboardJobs'),perf=document.querySelector('#performanceMetrics');
 try{
  const company=await getCompany();if(!company)throw new Error('Sessão empresarial necessária.');
  const [allJobs,apps]=await Promise.all([getCompanyJobs(company),getApplications(company)]),jobs=allJobs.filter(v=>v.status!=='excluida'),active=jobs.filter(v=>jobStatus(v)==='Ativa');
  const analysis=apps.filter(c=>['em avaliacao','em analise','analise'].some(x=>norm(c.status).includes(x))),interviews=apps.filter(c=>norm(c.status).includes('entrevista')),hires=apps.filter(c=>norm(c.status).includes('contratado')),approved=apps.filter(c=>norm(c.status).includes('aprovado'));
  document.querySelector('#companyWelcome').textContent='Olá, '+(company.nome||company.razao_social||'Empresa');
  const data=[['Vagas ativas',active.length,'Oportunidades publicadas'],['Candidaturas',apps.length,'Recebidas no total'],['Em análise',analysis.length,'Aguardando decisão'],['Entrevistas',interviews.length,'Etapa de entrevista'],['Contratações',hires.length,'Contratados registrados']];
  k.innerHTML=data.map(x=>`<a href="${x[0]==='Vagas ativas'?'./?pagina=vagas-empresa':'./?pagina=candidatos-empresa'}"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></a>`).join('');
  const processes=jobs.filter(v=>jobStatus(v)!=='Encerrada').slice(0,8);
  list.innerHTML=processes.length?processes.map(v=>{const cs=apps.filter(c=>String(c.vaga_id)===String(v.id)),ints=cs.filter(c=>norm(c.status).includes('entrevista')).length,hs=cs.filter(c=>norm(c.status).includes('contratado')).length;return `<article class="dash-job process-row"><div><strong>${esc(v.cargo||v.titulo||'Vaga')}</strong><small>${esc([v.cidade,v.estado||v.uf].filter(Boolean).join(' - ')||'Localização não informada')} · ${esc(jobStatus(v))}</small></div><span><b>${cs.length}</b> candidatos · ${ints} entrevistas · ${hs} contratação${hs===1?'':'ões'}</span><a href="./?pagina=candidatos-empresa&vaga=${encodeURIComponent(v.id)}">Ver candidaturas</a></article>`}).join(''):'<div class="empty"><strong>Nenhum processo em andamento</strong><p>Publique uma vaga para iniciar um novo recrutamento.</p></div>';
  const rate=(n,d)=>d?Math.round(n/d*100):0,advanced=apps.filter(c=>['entrevista','aprovado','contratado'].some(x=>norm(c.status).includes(x))).length;
  const metrics=[['Taxa de avanço',rate(advanced,apps.length)+'%','Candidatos que avançaram no processo'],['Entrevistas',interviews.length,String(rate(interviews.length,apps.length))+'% das candidaturas'],['Contratações',hires.length,String(rate(hires.length,apps.length))+'% das candidaturas'],['Candidatos',apps.length,approved.length+' aprovado'+(approved.length===1?'':'s')]];
  perf.innerHTML=metrics.map(x=>`<article><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');
 }catch(e){list.innerHTML='<div class="empty error"><strong>Não foi possível carregar o painel</strong><p>'+esc(e.message)+'</p></div>';k.innerHTML='';if(perf)perf.innerHTML=''}
}