import { getCompany,updateCompany } from '../services/supabase.js';
let company=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
export function renderCompanyProfile(){
 return `<main class="page profile-page"><header class="form-hero profile-hero"><span>PERFIL EMPRESARIAL</span><h1>Minha empresa</h1><p>Mantenha os dados institucionais e de recrutamento atualizados.</p></header><form id="companyForm" class="company-profile-form"><section class="profile-summary"><div id="companyLogo" class="company-logo">+</div><div><h2 id="companyName">Empresa</h2><p id="companyMeta">Carregando informações...</p><span id="verificationBadge">Perfil empresarial</span></div></section><div class="profile-layout"><div><section class="form-card"><div class="section-title"><b>1</b><div><h2>Identidade da empresa</h2><p>Informações exibidas no perfil público.</p></div></div><div class="form-grid"><label>Nome da empresa<input name="nome" required></label><label>Nome fantasia<input name="nome_fantasia"></label><label>Segmento<input name="setor" placeholder="Ex.: Comércio, Tecnologia, Saúde"></label><label>Número de funcionários<input name="funcionarios"></label><label class="wide">Sobre a empresa<textarea name="sobre" rows="7" placeholder="Conte aos candidatos sobre a empresa, cultura e ambiente de trabalho."></textarea></label><label class="wide">Site<input name="site" type="url" placeholder="https://"></label></div></section><section class="form-card"><div class="section-title"><b>2</b><div><h2>Localização</h2><p>Endereço principal da empresa.</p></div></div><div class="form-grid"><label>CEP<input name="cep"></label><label>Logradouro<input name="logradouro"></label><label>Número<input name="numero"></label><label>Bairro<input name="bairro"></label><label>Cidade<input name="cidade"></label><label>UF<input name="uf" maxlength="2"></label><label class="wide">Complemento<input name="complemento"></label></div></section></div><aside><section class="form-card sticky-card"><h2>Contato e recrutamento</h2><div class="form-stack"><label>E-mail corporativo<input name="email_corporativo" type="email"></label><label>E-mail para candidaturas<input name="email_candidaturas" type="email"></label><label>Telefone / WhatsApp<input name="telefone"></label><label>Responsável<input name="responsavel"></label><label>Função do responsável<input name="funcao_responsavel"></label></div><div class="account-box"><span>CNPJ</span><strong id="companyCnpj">—</strong><small>O CNPJ não pode ser alterado por esta tela.</small></div></section></aside></div><div id="profileMsg" class="form-msg"></div><div class="form-actions"><button id="saveCompany" type="submit">Salvar alterações</button></div></form></main>`;
}
function fill(c){const f=document.querySelector('#companyForm');for(const x of f.elements)if(x.name&&c[x.name]!=null)x.value=c[x.name]||'';document.querySelector('#companyName').textContent=c.nome||c.nome_fantasia||'Empresa';document.querySelector('#companyMeta').textContent=[c.setor,c.cidade,c.uf].filter(Boolean).join(' · ')||'Complete o perfil da empresa';document.querySelector('#companyCnpj').textContent=String(c.cnpj||'').replace(/(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})/,'$1.$2.$3/$4-$5')||'—';const badge=document.querySelector('#verificationBadge');if(c.verificada===true){badge.textContent='✓ Empresa verificada';badge.classList.add('verified')}const logo=document.querySelector('#companyLogo');if(c.logo_url)logo.innerHTML='<img src="'+esc(c.logo_url)+'" alt="Logo">';else logo.textContent=(c.nome||'E').slice(0,1).toUpperCase()}
export async function hydrateCompanyProfile(){
 const msg=document.querySelector('#profileMsg');try{company=await getCompany();if(!company)throw new Error('Sessão empresarial necessária.');fill(company);document.querySelector('#companyForm').onsubmit=save}catch(e){msg.textContent=e.message;msg.className='form-msg error'}}
async function save(ev){ev.preventDefault();const btn=document.querySelector('#saveCompany'),msg=document.querySelector('#profileMsg');btn.disabled=true;btn.textContent='Salvando...';try{const data=Object.fromEntries(new FormData(ev.currentTarget).entries());company=await updateCompany(company,data);fill(company);msg.textContent='Dados da empresa atualizados com sucesso.';msg.className='form-msg success'}catch(e){msg.textContent=e.message;msg.className='form-msg error'}finally{btn.disabled=false;btn.textContent='Salvar alterações'}}
