import { getCompany } from '../services/supabase.js';
const plans=[
 {id:'basico',name:'Grátis',price:'R$ 0,00',period:'Sem mensalidade',tag:'PARA COMEÇAR',jobs:'3 vagas por mês',features:['Candidaturas ilimitadas','Acesso aos currículos','Gestão de candidatos','Perfil da empresa','Painel do recrutador','Histórico das vagas','1 usuário'],extras:['Destaque avulso: R$ 19,90 / 7 dias','Urgência avulsa: R$ 9,90']},
 {id:'mensal',name:'Mensal',price:'R$ 49,90',period:'30 dias',tag:'FLEXÍVEL',jobs:'6 vagas por mês',features:['Todas as formas de candidatura','Painel completo','Gestão completa de candidatos','Estatísticas de recrutamento','1 Destaque por mês','1 Urgente por mês','Currículos online completos','Contato direto com candidatos']},
 {id:'trimestral',name:'Trimestral',price:'R$ 99,00',period:'Pagamento único · 3 meses',tag:'MAIS ECONOMIA',jobs:'12 vagas por mês',features:['Até 36 publicações em 3 meses','Todos os recursos do painel','Gestão completa de candidatos','Estatísticas completas','Recursos de visibilidade','Formas flexíveis de candidatura']},
 {id:'semestral',name:'Semestral',price:'R$ 179,00',period:'Pagamento único · 6 meses',tag:'MAIOR PERÍODO',jobs:'20 vagas por mês',features:['Até 120 publicações em 6 meses','Todos os recursos do painel','Gestão completa de candidatos','Indicadores de recrutamento','Recursos de visibilidade','Formas flexíveis de candidatura']}
];
export function renderPlans(){
 return `<main class="page plans-page"><header class="form-hero plans-hero"><span>PLANOS PARA EMPRESAS</span><h1>Escolha o plano para sua contratação</h1><p>Compare os recursos e a capacidade de publicação de cada opção.</p></header><div id="currentPlan" class="current-plan">Carregando seu plano...</div><section class="plans-grid">${plans.map(p=>`<article class="plan-card" data-plan="${p.id}"><div class="plan-tag">${p.tag}</div><h2>${p.name}</h2><div class="plan-price">${p.price}</div><p>${p.period}</p><strong class="plan-jobs">${p.jobs}</strong><ul>${p.features.map(x=>'<li>✓ '+x+'</li>').join('')}</ul>${p.extras?'<div class="plan-extras">'+p.extras.map(x=>'<small>'+x+'</small>').join('')+'</div>':''}<button type="button" data-select="${p.id}">Escolher ${p.name}</button></article>`).join('')}</section><section class="plans-note"><h2>Todos os planos foram pensados para recrutamento direto</h2><p>A empresa pode gerenciar suas vagas e candidatos pelo painel. Recursos disponíveis variam conforme o plano contratado e o período de vigência.</p></section><div id="planMsg" class="form-msg"></div></main>`;
}
export async function hydratePlans(){
 const cur=document.querySelector('#currentPlan'),msg=document.querySelector('#planMsg');try{const c=await getCompany();if(!c)throw new Error('Sessão empresarial necessária.');const id=c.plano_id||c.plano||'basico',p=plans.find(x=>x.id===id)||plans[0];cur.innerHTML='<div><span>SEU PLANO ATUAL</span><strong>'+p.name+'</strong><small>'+p.jobs+' · '+p.period+'</small></div><a href="./?pagina=vagas-empresa">Gerenciar minhas vagas</a>';document.querySelector('[data-plan="'+p.id+'"]')?.classList.add('current');document.querySelectorAll('[data-select]').forEach(b=>{if(b.dataset.select===p.id){b.textContent='Plano atual';b.disabled=true}else b.onclick=()=>{msg.textContent='Plano '+(plans.find(x=>x.id===b.dataset.select)?.name||'')+' selecionado. A próxima etapa será conectar a contratação/pagamento.';msg.className='form-msg success'}})}catch(e){cur.textContent=e.message;cur.classList.add('error')}}
