import { getCompany,getCompanyJobs,planUsage } from '../services/supabase.js';
const plans=[
 {id:'basico',name:'Grátis',price:'R$ 0,00',period:'Sem mensalidade',tag:'PARA COMEÇAR',jobs:'3 vagas por mês',features:['Candidaturas ilimitadas','Acesso aos currículos','Gestão de candidatos','Perfil da empresa','Painel do recrutador','Histórico das vagas','1 usuário'],extras:['Destaque avulso: R$ 19,90 / 7 dias','Urgência avulsa: R$ 9,90']},
 {id:'mensal',name:'Mensal',price:'R$ 49,90',period:'30 dias',tag:'FLEXÍVEL',jobs:'6 vagas por mês',features:['Todas as formas de candidatura','Painel completo','Gestão completa de candidatos','Estatísticas de recrutamento','1 Destaque por mês','1 Urgente por mês','Currículos online completos','Contato direto com candidatos']},
 {id:'trimestral',name:'Trimestral',price:'R$ 99,00',period:'Pagamento único · 3 meses',tag:'MAIS ECONOMIA',jobs:'12 vagas por mês',features:['Até 36 publicações em 3 meses','Todos os recursos do painel','Gestão completa de candidatos','Estatísticas completas','Recursos de visibilidade','Formas flexíveis de candidatura']},
 {id:'semestral',name:'Semestral',price:'R$ 179,90',period:'Pagamento único · 6 meses',tag:'MAIOR PERÍODO',jobs:'25 vagas por período',features:['25 publicações no período','5 Destaques','5 Urgências','4 vagas Confidenciais','Todos os recursos do painel','Indicadores de recrutamento']},
 {id:'anual',name:'Anual',price:'R$ 329,00',period:'Pagamento único · 12 meses',tag:'MELHOR PERÍODO',jobs:'60 vagas por período',features:['60 publicações no período','10 Destaques','10 Urgências','8 vagas Confidenciais','Todos os recursos do painel','Indicadores de recrutamento']}
];
export function renderPlans(){
 return `<main class="page plans-page"><header class="form-hero plans-hero"><span>PLANOS PARA EMPRESAS</span><h1>Escolha o plano para sua contratação</h1><p>Compare os recursos e a capacidade de publicação de cada opção.</p></header><div id="currentPlan" class="current-plan">Carregando seu plano...</div><section class="plans-grid">${plans.map(p=>`<article class="plan-card" data-plan="${p.id}"><div class="plan-tag">${p.tag}</div><h2>${p.name}</h2><div class="plan-price">${p.price}</div><p>${p.period}</p><strong class="plan-jobs">${p.jobs}</strong><ul>${p.features.map(x=>'<li>✓ '+x+'</li>').join('')}</ul>${p.extras?'<div class="plan-extras">'+p.extras.map(x=>'<small>'+x+'</small>').join('')+'</div>':''}<button type="button" data-select="${p.id}">Escolher ${p.name}</button></article>`).join('')}</section><section class="plans-note"><h2>Todos os planos foram pensados para recrutamento direto</h2><p>A empresa pode gerenciar suas vagas e candidatos pelo painel. Recursos disponíveis variam conforme o plano contratado e o período de vigência.</p></section><div id="planMsg" class="form-msg"></div></main>`;
}
export async function hydratePlans(){
 const cur=document.querySelector('#currentPlan'),msg=document.querySelector('#planMsg');
 try{
  const c=await getCompany();if(!c)throw new Error('Sessão empresarial necessária.');const jobs=await getCompanyJobs(c),usage=planUsage(c,jobs),id=c.plano_id||c.plano||'basico',p=plans.find(x=>x.id===id)||plans[0],lim=usage.plano;
  const until=c.plano_valido_ate||c.assinatura_fim||'',valid=until?' · válido até '+new Date(until+'T12:00:00').toLocaleDateString('pt-BR'):'';
  cur.innerHTML='<div><span>SEU PLANO ATUAL</span><strong>'+p.name+'</strong><small>'+p.period+valid+'</small></div><div class="plan-balance"><b>'+(Math.max(0,lim.vagas-usage.vagas))+' vagas</b><span>'+Math.max(0,lim.destaques-usage.destaques)+' destaques · '+Math.max(0,lim.urgentes-usage.urgentes)+' urgências</span></div><a href="./?pagina=vagas-empresa">Gerenciar vagas</a>';
  document.querySelector('[data-plan="'+p.id+'"]')?.classList.add('current');
  document.querySelectorAll('[data-select]').forEach(b=>{if(b.dataset.select===p.id){b.textContent='Plano atual';b.disabled=true}else b.onclick=()=>openCheckout(b.dataset.select,msg)});
 }catch(e){cur.textContent=e.message;cur.classList.add('error')}
}
function openCheckout(id,msg){
 const p=plans.find(x=>x.id===id);if(!p)return;if(id==='basico'){msg.textContent='Alterações para o plano Grátis devem respeitar a vigência do plano atual. Nenhum plano será alterado automaticamente.';msg.className='form-msg error';return}
 document.querySelector('#planCheckout')?.remove();const raw={mensal:49.9,trimestral:99,semestral:179.9,anual:329}[id]||0,pix=raw*.94,br=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
 const d=document.createElement('div');d.id='planCheckout';d.className='cv-modal';d.innerHTML='<div class="cv-back"></div><section class="checkout-box"><button class="cv-close">×</button><span>RESUMO DA CONTRATAÇÃO</span><h2>Plano '+p.name+'</h2><p>O plano atual só será alterado depois que o pagamento for confirmado pelo sistema.</p><div class="checkout-price"><span>Valor</span><strong>'+br(raw)+'</strong></div><label class="checkout-pay"><input type="radio" name="pay" value="pix" checked><div><b>Pix · 6% de desconto</b><small>'+br(pix)+' à vista</small></div></label><label class="checkout-pay"><input type="radio" name="pay" value="cartao"><div><b>Cartão de crédito</b><small>Até 3x de '+br(raw/3)+'</small></div></label><div class="checkout-warning">A integração de pagamento ainda não está conectada na V2. Esta tela não ativa nem cobra nenhum plano.</div><button class="checkout-continue" type="button">Pagamento ainda não disponível</button></section>';document.body.appendChild(d);d.querySelector('.cv-back').onclick=d.querySelector('.cv-close').onclick=()=>d.remove();d.querySelector('.checkout-continue').disabled=true;
}